parameters:
#    rhox_admin.example.class: Rhox\AdminBundle\Example

services:
#    rhox_admin.example:
#        class: %rhox_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
